//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        Test.ServiceReference.SignInResponse SignIn(Test.ServiceReference.SignInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.ServiceReference.SignInResponse> SignInAsync(Test.ServiceReference.SignInRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestFiles", ReplyAction="*")]
        Test.ServiceReference.RequestFilesResponse RequestFiles(Test.ServiceReference.RequestFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestFiles", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.ServiceReference.RequestFilesResponse> RequestFilesAsync(Test.ServiceReference.RequestFilesRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignOut", ReplyAction="*")]
        Test.ServiceReference.SignOutResponse SignOut(Test.ServiceReference.SignOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignOut", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.ServiceReference.SignOutResponse> SignOutAsync(Test.ServiceReference.SignOutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignIn", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference.SignInRequestBody Body;
        
        public SignInRequest() {
        }
        
        public SignInRequest(Test.ServiceReference.SignInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public SignInRequestBody() {
        }
        
        public SignInRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference.SignInResponseBody Body;
        
        public SignInResponse() {
        }
        
        public SignInResponse(Test.ServiceReference.SignInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SignInResult;
        
        public SignInResponseBody() {
        }
        
        public SignInResponseBody(bool SignInResult) {
            this.SignInResult = SignInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestFiles", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference.RequestFilesRequestBody Body;
        
        public RequestFilesRequest() {
        }
        
        public RequestFilesRequest(Test.ServiceReference.RequestFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestFilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public RequestFilesRequestBody() {
        }
        
        public RequestFilesRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestFilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference.RequestFilesResponseBody Body;
        
        public RequestFilesResponse() {
        }
        
        public RequestFilesResponse(Test.ServiceReference.RequestFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestFilesResult;
        
        public RequestFilesResponseBody() {
        }
        
        public RequestFilesResponseBody(string RequestFilesResult) {
            this.RequestFilesResult = RequestFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignOut", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference.SignOutRequestBody Body;
        
        public SignOutRequest() {
        }
        
        public SignOutRequest(Test.ServiceReference.SignOutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignOutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public SignOutRequestBody() {
        }
        
        public SignOutRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignOutResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference.SignOutResponseBody Body;
        
        public SignOutResponse() {
        }
        
        public SignOutResponse(Test.ServiceReference.SignOutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignOutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SignOutResult;
        
        public SignOutResponseBody() {
        }
        
        public SignOutResponseBody(bool SignOutResult) {
            this.SignOutResult = SignOutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Test.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Test.ServiceReference.WebServiceSoap>, Test.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference.SignInResponse Test.ServiceReference.WebServiceSoap.SignIn(Test.ServiceReference.SignInRequest request) {
            return base.Channel.SignIn(request);
        }
        
        public bool SignIn(string xml) {
            Test.ServiceReference.SignInRequest inValue = new Test.ServiceReference.SignInRequest();
            inValue.Body = new Test.ServiceReference.SignInRequestBody();
            inValue.Body.xml = xml;
            Test.ServiceReference.SignInResponse retVal = ((Test.ServiceReference.WebServiceSoap)(this)).SignIn(inValue);
            return retVal.Body.SignInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.ServiceReference.SignInResponse> Test.ServiceReference.WebServiceSoap.SignInAsync(Test.ServiceReference.SignInRequest request) {
            return base.Channel.SignInAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference.SignInResponse> SignInAsync(string xml) {
            Test.ServiceReference.SignInRequest inValue = new Test.ServiceReference.SignInRequest();
            inValue.Body = new Test.ServiceReference.SignInRequestBody();
            inValue.Body.xml = xml;
            return ((Test.ServiceReference.WebServiceSoap)(this)).SignInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference.RequestFilesResponse Test.ServiceReference.WebServiceSoap.RequestFiles(Test.ServiceReference.RequestFilesRequest request) {
            return base.Channel.RequestFiles(request);
        }
        
        public string RequestFiles(string xml) {
            Test.ServiceReference.RequestFilesRequest inValue = new Test.ServiceReference.RequestFilesRequest();
            inValue.Body = new Test.ServiceReference.RequestFilesRequestBody();
            inValue.Body.xml = xml;
            Test.ServiceReference.RequestFilesResponse retVal = ((Test.ServiceReference.WebServiceSoap)(this)).RequestFiles(inValue);
            return retVal.Body.RequestFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.ServiceReference.RequestFilesResponse> Test.ServiceReference.WebServiceSoap.RequestFilesAsync(Test.ServiceReference.RequestFilesRequest request) {
            return base.Channel.RequestFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference.RequestFilesResponse> RequestFilesAsync(string xml) {
            Test.ServiceReference.RequestFilesRequest inValue = new Test.ServiceReference.RequestFilesRequest();
            inValue.Body = new Test.ServiceReference.RequestFilesRequestBody();
            inValue.Body.xml = xml;
            return ((Test.ServiceReference.WebServiceSoap)(this)).RequestFilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference.SignOutResponse Test.ServiceReference.WebServiceSoap.SignOut(Test.ServiceReference.SignOutRequest request) {
            return base.Channel.SignOut(request);
        }
        
        public bool SignOut(string xml) {
            Test.ServiceReference.SignOutRequest inValue = new Test.ServiceReference.SignOutRequest();
            inValue.Body = new Test.ServiceReference.SignOutRequestBody();
            inValue.Body.xml = xml;
            Test.ServiceReference.SignOutResponse retVal = ((Test.ServiceReference.WebServiceSoap)(this)).SignOut(inValue);
            return retVal.Body.SignOutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.ServiceReference.SignOutResponse> Test.ServiceReference.WebServiceSoap.SignOutAsync(Test.ServiceReference.SignOutRequest request) {
            return base.Channel.SignOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference.SignOutResponse> SignOutAsync(string xml) {
            Test.ServiceReference.SignOutRequest inValue = new Test.ServiceReference.SignOutRequest();
            inValue.Body = new Test.ServiceReference.SignOutRequestBody();
            inValue.Body.xml = xml;
            return ((Test.ServiceReference.WebServiceSoap)(this)).SignOutAsync(inValue);
        }
    }
}
